sudo: false
language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby-19mode

notifications:
  recipients:
    - weppos@weppos.net

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
  include:
    - rvm: 1.9.2
      gemfile: Gemfile.ruby-1.9.2
